export { default as Home } from './Home/Home'
export { default as NewPost } from './NewPost/NewPost'
export { default as TextForm } from './TextForm/TextForm'
export { default as ButtonForm } from './ButtonForm/ButtonForm'
export { default as Loading } from './Loading/Loading'
export { default as Modal } from './Modal/Modal'
export { default as AutoCompleteForm } from './AutoCompleteForm/AutoCompleteForm'
